### ISSUE TITLE
reportstate table needs report_count reset to 0 when beer/establishment status is updated by admin

### ISSUE THREAD

**Issue by pagan8** [AthensWorks/OBWapp-Admin-UI#3]
Ben had me add a counter to reportstate table to not reject multiple requests from the user that were duplicates, instead we count them. However these need to be reset if a beer / establishment status is changed, otherwise that user's device_guid won't be able to report the beer out again :)

so you need to add support for changing beer + establishment status from empty_report to anything else where you were clearing the reported out count to also set report_state = 0 for all entries in reportstate table where beer_id and establishment_id match that pair..

make sense? :)

**Comment by rickychilcott** [comment]
upon status update, do the following:
- `status.report_countdown = 0`
- `ReportState.where(establishment_id: status.establishment_id, beer_id: status.beer_id).update_all(report_count: 0)`
